#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# The Pi's ssh name is in local.env (never committed), e.g. PI=raspberrypi
PI="${PI:-$(sed -n 's/^PI=//p' "$(dirname "$0")/../local.env" 2>/dev/null || true)}"
: "${PI:?Sett PI=<ssh-navnet til Pi-en> i local.env}"
REMOTE_ENV=".config/vaktkalender/config.env"

# The config lives on the Pi. Work on a private local copy and push it back after each stage.
ENV_FILE="$(mktemp)"
chmod 600 "$ENV_FILE"
trap 'rm -f "$ENV_FILE"' EXIT
scp -q "$PI:$REMOTE_ENV" "$ENV_FILE" || { echo "Fikk ikke hentet $REMOTE_ENV fra $PI. Kjør ./deploy.sh først."; exit 1; }

# The site's address comes from PUBLIC_URL in the Pi's config, e.g. vakt.example.com → subdomain "vakt".
HOST=$(sed -n 's/^PUBLIC_URL=//p' "$ENV_FILE" | tr -d "\"'" | sed -E 's#^https?://##; s#/.*$##')
[[ -n "$HOST" && "$HOST" != "vakt.example.com" ]] || { echo "Sett PUBLIC_URL i ~/$REMOTE_ENV på $PI først."; exit 1; }
SUBDOMAIN="${HOST%%.*}"
DOMAIN="${HOST#*.}"

push_config() {
  scp -q "$ENV_FILE" "$PI:$REMOTE_ENV"
  ssh "$PI" "chmod 600 ~/$REMOTE_ENV && systemctl --user restart vaktkalender-web"
  printf '  %s✓ config lagret på Pi-en%s\n' "$GREEN" "$RESET"
}

on_pi() {  # run a vaktkalender command on the Pi with its config loaded
  ssh "$PI" "cd ~/vaktkalender/app && set -a && . ~/$REMOTE_ENV && set +a && ../.venv/bin/python -m vaktkalender $*"
}

banner "Vaktkalender: Telegram, Google og Cloudflare"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Telegram: lag en bot"
say "Boten sender deg varsler (RBU-innlogging utløpt, ny måned publisert, feil)."
open_url "https://t.me/BotFather"
step "I Telegram, i chatten med @BotFather: send /newbot"
step "Navn: Vaktkalender   ·   Brukernavn: noe som slutter på «bot», f.eks. vaktkalender_dittnavn_bot"
step "BotFather svarer med et token (ser ut som 123456789:AAH...). Kopier det."
while true; do
  ask_secret TELEGRAM_BOT_TOKEN "Lim inn bot-tokenet:"
  if curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" >/dev/null 2>&1; then break; fi
  warn "Telegram godtok ikke tokenet. Prøv igjen."
done
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Telegram: koble boten til deg"
step "Åpne boten din i Telegram (lenken står i BotFather-svaret), trykk Start og send «hei»."
pause "Trykk Enter når du har sendt «hei» til boten."
TELEGRAM_CHAT_ID=""
while [[ -z "$TELEGRAM_CHAT_ID" ]]; do
  TELEGRAM_CHAT_ID=$(curl -fsS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates" |
    python3 -c 'import json,sys; u=json.load(sys.stdin)["result"]; print(next((x["message"]["chat"]["id"] for x in reversed(u) if "message" in x), ""))' || true)
  if [[ -z "$TELEGRAM_CHAT_ID" ]]; then
    warn "Fant ingen melding ennå. Send «hei» til boten og trykk Enter."
    pause ""
  fi
done
write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
push_config
if on_pi test-telegram >/dev/null 2>&1; then
  confirm "Fikk du «✅ Vaktkalender kan sende meldinger til deg.» i Telegram?" || warn "Sjekk token/chat-id senere med: ssh $PI … python -m vaktkalender test-telegram"
else
  warn "Telegram tok ikke imot testmeldingen. Kjør ./scripts/setup_telegram.sh senere for å se feilen."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: prosjekt og Calendar API"
say "Gratis, ingen betalingskort. Logg inn med din egen Google-konto."
open_url "https://console.cloud.google.com/projectcreate"
step "Prosjektnavn: vaktkalender → Create. Vent til prosjektet er laget og valgt øverst til venstre."
pause "Trykk Enter når prosjektet er laget."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Sjekk at prosjektet «vaktkalender» er valgt øverst → trykk Enable."
pause "Trykk Enter når Google Calendar API står som Enabled."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: service account (roboten som eier kalenderne)"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create"
step "Service account name: vaktkalender → Create and continue"
step "Hopp over «Permissions» og «Principals with access» → Done (ingen roller trengs)."
step "Klikk på den nye kontoen → fanen Keys → Add key → Create new key → JSON → Create."
step "En .json-fil lastes ned. Den er hemmelig – den flyttes til Pi-en og slettes fra Macen."
note "Står det «Service account key creation is disabled»? Si fra – da trengs en innstilling til."
LATEST=$(ls -t "$HOME"/Downloads/*.json 2>/dev/null | head -n1 || true)
while true; do
  printf '  %sSti til nøkkelfilen%s %s[Enter = %s]%s ' "$BOLD" "$RESET" "$DIM" "${LATEST:-ingen funnet}" "$RESET"
  read -r KEY_FILE || true
  KEY_FILE="${KEY_FILE:-$LATEST}"
  KEY_FILE="${KEY_FILE/#\~/$HOME}"
  if [[ -f "$KEY_FILE" ]] && python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); assert d["type"]=="service_account"; print("  → "+d["client_email"])' "$KEY_FILE"; then break; fi
  warn "Det er ikke en service account-nøkkel. Prøv igjen."
done
scp -q "$KEY_FILE" "$PI:.config/vaktkalender/google-service-account.json"
ssh "$PI" "chmod 600 ~/.config/vaktkalender/google-service-account.json"
write_env GOOGLE_SERVICE_ACCOUNT_FILE "~/.config/vaktkalender/google-service-account.json"
push_config
CHECK=$(on_pi check 2>/dev/null || true)
if grep -q "^OK   Google" <<<"$CHECK"; then
  printf '  %s✓ Pi-en snakker med Google Calendar%s\n' "$GREEN" "$RESET"
  confirm "Slette nøkkelfilen fra Macen nå ($KEY_FILE)?" && rm -f "$KEY_FILE" && say "Slettet."
else
  warn "Google-sjekken feilet. Kjør check senere: ssh $PI → python -m vaktkalender check"
  pause
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: koble subdomenet til Pi-en"
open_url "https://one.dash.cloudflare.com/"
step "Networks → Tunnels (heter også «Connectors»). Klikk tunnelen (cloudflared) som kjører på Pi-en → Edit."
step "Fanen «Public Hostname» (kan hete «Published application routes») → Add."
step "Subdomain: $SUBDOMAIN   ·   Domain: $DOMAIN   ·   Path: (tom)"
step "Service → Type: HTTP   ·   URL: localhost:8090   → Save"
note "Siden er trygg selv før neste steg: appen avviser alle uten gyldig Cloudflare Access-innlogging."
pause "Trykk Enter når hostnavnet er lagret."
for _ in 1 2 3 4 5 6; do
  if [[ "$(curl -s -m 10 "https://$HOST/healthz" || true)" == "ok" ]]; then
    printf '  %s✓ https://%s når Pi-en%s\n' "$GREEN" "$HOST" "$RESET"; REACHED=1; break
  fi
  sleep 5
done
[[ -n "${REACHED:-}" ]] || { warn "Fikk ikke kontakt med https://$HOST ennå. Sjekk Service-URL: localhost:8090."; pause; }

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access: hvem slipper inn"
open_url "https://one.dash.cloudflare.com/"
step "Settings → Authentication → Login methods: sjekk at «One-time PIN» finnes (Add new → One-time PIN hvis ikke)."
step "Access → Applications → Add an application → Self-hosted."
step "Application name: Vaktkalender   ·   Session duration: 1 month"
step "Public hostname: subdomain $SUBDOMAIN, domain $DOMAIN"
step "Policy: navn «Kolleger», Action: Allow, Include → Emails → din e-post + kollegenes Google-adresser"
step "Login methods: One-time PIN → lagre applikasjonen."
step "Åpne applikasjonen igjen → Overview/Basic information → kopier «Application Audience (AUD) Tag»."
ask CF_ACCESS_AUD "Lim inn AUD-taggen:"
write_env CF_ACCESS_AUD "$CF_ACCESS_AUD"
step "Settings → Custom Pages (eller «Team name and domain»): teamdomenet, f.eks. dittnavn.cloudflareaccess.com"
ask CF_ACCESS_TEAM_DOMAIN "Teamdomenet (uten https://):"
CF_ACCESS_TEAM_DOMAIN="${CF_ACCESS_TEAM_DOMAIN#https://}"
CF_ACCESS_TEAM_DOMAIN="${CF_ACCESS_TEAM_DOMAIN%/}"
write_env CF_ACCESS_TEAM_DOMAIN "$CF_ACCESS_TEAM_DOMAIN"
push_config
if curl -s -o /dev/null -m 10 -w '%{redirect_url}' "https://$HOST/" | grep -q cloudflareaccess.com; then
  printf '  %s✓ Siden krever nå innlogging%s\n' "$GREEN" "$RESET"
else
  warn "Siden sendte ikke til Cloudflare-innlogging ennå. Sjekk at Access-applikasjonen er lagret."
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access: slipp kalender-appene inn på /ics/"
say "Google og Apple henter kalenderen uten å logge inn. Lenken har en lang hemmelig nøkkel i seg."
step "Access → Applications → Add an application → Self-hosted."
step "Application name: Vaktkalender – feed"
step "Public hostname: subdomain $SUBDOMAIN, domain $DOMAIN, Path: ics/*"
step "Policy: navn «Kalender-apper», Action: Bypass, Include → Everyone → lagre."
pause "Trykk Enter når den er lagret."
FEED_CHECK=$(curl -s -o /dev/null -m 10 -w '%{http_code} %{redirect_url}' "https://$HOST/ics/sjekk.ics" || true)
if [[ "$FEED_CHECK" == 404* ]]; then
  printf '  %s✓ /ics/ går forbi innloggingen (og ukjente nøkler gir 404)%s\n' "$GREEN" "$RESET"
else
  warn "Fikk «$FEED_CHECK» – forventet 404 fra appen. Sjekk Path: ics/* og Action: Bypass."
fi
say ""
say "Sluttsjekk på Pi-en:"
on_pi check || true
pause "Trykk Enter for å avslutte."

finish
say "Åpne https://$HOST, logg inn med e-postkoden, og test selv først."
say "Nye kolleger: legg til Google-adressen deres i Access-policyen «Kolleger»."
printf '\n'
